### ISSUE TITLE
GPU issue with PAScall

### ISSUE THREAD

**Issue by lakewoo** [YangLab/SCAPTURE#10]
Hi,

I ran into an issue related with GPU when running PAScall with the test dataset PBMC3K on my server. Our server doesn't have any GPUs installed. I saw another post mentioned that it will use CPU if there is no available GPU. So I am wondering do you suggestion to get rid of this issue for my case? Thanks!

Here is the log file from "PBMC3K.exonic.peaks.DeepPASS.predict.log":

2022-10-19 13:04:06.688118: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2699950000 Hz
2022-10-19 13:04:06.693677: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55fd635f5ef0 executing computations on platform Host. Devices:
2022-10-19 13:04:06.693779: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2022-10-19 13:04:06.718258: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib:/usr/local/lib:/usr/local/gmp/5.1.1/lib64:/gpfs/tools/gsl/lib:/gpfs/tools/icu58/lib/:/gpfs/tools/anaconda/lib:/gpfs/tools/gsl/lib:/gpfs/tools/libiconv-1.15/lib
2022-10-19 13:04:06.718430: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-19 13:04:06.718510: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (amber): /proc/driver/nvidia/version does not exist

********************** Start Data Processing **************************
Traceback (most recent call last):
  File "/home/jingting/gpfs_analyses/UCSD_Hao/SCAPTURE/DeepPASS/Predict.py", line 69, in <module>
    dataset_pre = pd.read_csv(pre_f,sep='\t',index_col = False,header = None)
  File "/gpfs/tools/anaconda/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/gpfs/tools/anaconda/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/gpfs/tools/anaconda/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/gpfs/tools/anaconda/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/gpfs/tools/anaconda/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by liguowei-CAS** [comment]
Plz try the command below in your environment to check bedtools :

`bedtools getfasta -fi ../annotation/GRCh38.p13.genome.fa -bed PBMC3k.exonic.peaks.annotated.bed -s -split -name > PBMC3k.exonic.peaks.annotated.fa
`
We recommend bedtools 2.26.0 for SCAPTURE:
`conda install -c biobuilds bedtools
`
If I can be of assistance, please do not hesitate to contact me.
