### ISSUE TITLE
Issue with PAScall on test data

### ISSUE THREAD

**Issue by Hira8023** [YangLab/SCAPTURE#11]
Hi,
I am running PAScall on PBCK4k.test.bam,but the PBMC4k.PAScall.log showed something wrong:
scapture path: /mnt/data2/zhouxl/APA/SCAPTURE/SCAPTURE-main/
DeepPASS model file dir: /mnt/data2/zhouxl/APA/SCAPTURE/SCAPTURE-main/DeepPASS/
scapture module: PAScall
Output prefix: PBMC4k
prefix of annotation files from annotation module: SCAPTURE_annotation
BAM file: PBMC4k.test.bam
Fragment length: 98
GENOME file: GRCh38.p13.genome.fa
Peak width: 400
OverlapRatio: 0.5
threads: 16
poly(a) database file: SupTab_KnownPASs_fourDBs.txt
scapture PAScall: create command line. Fri Nov 11 10:25:01 CST 2022
scapture PAScall: create command line done. Fri Nov 11 10:25:14 CST 2022
scapture PAScall: peak calling. Fri Nov 11 10:25:14 CST 2022
scapture PAScall: peak calling done. Fri Nov 11 10:31:44 CST 2022
scapture PAScall: peak annotating. Fri Nov 11 10:31:44 CST 2022
scapture PAScall: peak annotating done. Fri Nov 11 10:31:49 CST 2022
scapture PAScall: PAS evaluating. Fri Nov 11 10:31:49 CST 2022
Species is not currently supported in DeepPASS, use human model instead !
cat: PBMC4k.exonic.peaks.DeepPASS.predictout/Predict_Result.txt: No such file or directory
Species is not currently supported in DeepPASS, use human model instead !
cat: PBMC4k.intronic.peaks.DeepPASS.predictout/Predict_Result.txt: No such file or directory
Species is not currently supported in DeepPASS, use human model instead !
cat: PBMC4k.3primeExtended.peaks.DeepPASS.predictout/Predict_Result.txt: No such file or directory
scapture PAScall: output files --  PBMC4k.exonic.peaks.evaluated.bed PBMC4k.intronic.peaks.evaluated.bed PBMC4k.3primeExtended.peaks.evaluated.bed
scapture PAScall: PAS evaluating done. Fri Nov 11 12:21:14 CST 2022

and the DeepPASS.log showed wrong:
********************** Start Data Processing **************************

********************** Finished Data Processing ***********************

************************* Start Prediction ****************************
Traceback (most recent call last):
  File "/mnt/data2/zhouxl/APA/SCAPTURE/SCAPTURE-main/DeepPASS/Predict.py", line 89, in <module>
    prediction = best_model.predict(PredictSet["seq"])
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 462, in predict
    steps=steps, callbacks=callbacks, **kwargs)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
    total_epochs=1)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node sequential/conv1d/conv1d (defined at home/xiaolan/.local/share/r-miniconda/envs/SCAPTURE_env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_distributed_function_3649]
Function call stack:
distributed_function

and when using my own data, the PAScall.log also have someting wrong:
scapture path: /mnt/data2/zhouxl/APA/SCAPTURE/SCAPTURE-main/
DeepPASS model file dir: /mnt/data2/zhouxl/APA/SCAPTURE/SCAPTURE-main/DeepPASS/
scapture module: PAScall
Output prefix: 144
prefix of annotation files from annotation module: SCAPTURE_annotation
BAM file: 144.possorted_genome_bam.bam
Fragment length: 98
GENOME file: GRCh38.p13.genome.fa
Peak width: 400
OverlapRatio: 0.5
threads: 16
poly(a) database file: SupTab_KnownPASs_fourDBs.txt
scapture PAScall: create command line. Fri Nov 11 10:50:41 CST 2022
scapture PAScall: create command line done. Fri Nov 11 10:55:43 CST 2022
scapture PAScall: peak calling. Fri Nov 11 10:55:43 CST 2022
sort: cannot read: 144_tmp/144.exonic.peak.isoform.tmp: No such file or directory
rm: cannot remove '144_tmp/144.exonic.peak.isoform.tmp': No such file or directory
sort: cannot read: 144_tmp/144.exonic.peak.isoform.normality.tmp: No such file or directory
rm: cannot remove '144_tmp/144.exonic.peak.isoform.normality.tmp': No such file or directory
sort: cannot read: 144_tmp/144.exonic.peak.isoform.normality.aggregate.tmp: No such file or directory
rm: cannot remove '144_tmp/144.exonic.peak.isoform.normality.aggregate.tmp': No such file or directory
sort: cannot read: 144_tmp/144.exonic.peaks.tmp: No such file or directory
rm: cannot remove '144_tmp/144.exonic.peaks.tmp': No such file or directory
sort: cannot read: 144_tmp/144.intronic.rawpeak.tmp: No such file or directory
rm: cannot remove '144_tmp/144.intronic.rawpeak.tmp': No such file or directory
sort: cannot read: 144_tmp/144.intronic.peak.aggregate.tmp: No such file or directory
rm: cannot remove '144_tmp/144.intronic.peak.aggregate.tmp': No such file or directory
sort: cannot read: 144_tmp/144.intronic.peaks.tmp: No such file or directory
rm: cannot remove '144_tmp/144.intronic.peaks.tmp': No such file or directory
scapture PAScall: peak calling done. Fri Nov 11 11:58:25 CST 2022
scapture PAScall: peak annotating. Fri Nov 11 11:58:25 CST 2022
scapture PAScall: peak annotating done. Fri Nov 11 11:58:31 CST 2022
scapture PAScall: PAS evaluating. Fri Nov 11 11:58:31 CST 2022
cat: 144.exonic.peaks.DeepPASS.predictout/Predict_Result.txt: No such file or directory
***** ERROR: too many digits/characters for integer conversion in string . Exiting...
cat: 144.intronic.peaks.DeepPASS.predictout/Predict_Result.txt: No such file or directory
***** ERROR: too many digits/characters for integer conversion in string . Exiting...
cat: 144.3primeExtended.peaks.DeepPASS.predictout/Predict_Result.txt: No such file or directory
***** ERROR: too many digits/characters for integer conversion in string . Exiting...
scapture PAScall: output files --  144.exonic.peaks.evaluated.bed 144.intronic.peaks.evaluated.bed 144.3primeExtended.peaks.evaluated.bed
scapture PAScall: PAS evaluating done. Fri Nov 11 11:58:40 CST 2022

 I don't know how to solve it, any reply is appreciated!

**Comment by Pei-Hong** [comment]
Hi,
The first issue may arise when the the versions of cuda and tensorflow do not match. About the second issue, you can read line228 in the script (https://github.com/YangLab/SCAPTURE/blob/main/scapture), and run one command in $PREFIX".CallPasPerGene.sh", it would be easier to know what happens during the PAS calling.
Hope it's helpful. If other questions arise, please no hesitate to contact me. :)
