### ISSUE TITLE
Yaml file not working in WSL

### ISSUE THREAD

**Issue by rbarbieri86** [YangLab/SCAPTURE#12]
Hello, I was trying to create the SCAPTURE env with conda as per instructions, however the yaml file downloaded caused a lengthy error message from conda:

`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 103, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 47, in detect
        if spec.can_handle():
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 19, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 169, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 50, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/home/rbarb/anaconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 195, column 75:
         ... age-responsive" style="word-wrap: break-word;">
                                             ^ (line: 195)

`$ /home/rbarb/anaconda3/bin/conda-env create -f SCAPTURE_env.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/rbarb/anaconda3/bin/conda
             CONDA_PREFIX=/home/rbarb/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/rbarb/anaconda3/bin/python
               CONDA_ROOT=/home/rbarb/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/rbarb/.local/bin:/home/rbarb/.local/bin:/home/rbarb/anaconda3/bi
                          n:/home/rbarb/anaconda3/condabin:/home/rbarb/.local/bin:/usr/local/sbi
                          n:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/g
                          ames:/usr/lib/wsl/lib:/mnt/c/Program Files (x86)/Common Files/Oracle/J
                          ava/javapath:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/Sys
                          tem32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0:/mnt/c/windo
                          ws/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/Phys
                          X/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System3
                          2/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/S
                          ystem32/OpenSSH:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt
                          /c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.
                          0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Users/RBarbieri/AppData/Local
                          /Microsoft/WindowsApps:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/rbarb/anaconda3
            shell level : 1
       user config file : /home/rbarb/.condarc
 populated config files : /home/rbarb/.condarc
          conda version : 22.9.0
    conda-build version : 3.24.0
         python version : 3.9.7.final.0
       virtual packages : __cuda=12.2=0
                          __linux=5.10.16.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rbarb/anaconda3  (writable)
      conda av data dir : /home/rbarb/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rbarb/anaconda3/pkgs
                          /home/rbarb/.conda/pkgs
       envs directories : /home/rbarb/anaconda3/envs
                          /home/rbarb/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.26.0 CPython/3.9.7 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False`

Anything that can be done about this?

Thank you in advance!

**Comment by Pei-Hong** [comment]
We didn't test the pipeline in WSL. It's recommended to run in linux directly.
