### ISSUE TITLE
GPU or CPU for PAScall step?

### ISSUE THREAD

**Issue by YangShi-PKU** [YangLab/SCAPTURE#7]
Hi guowei,
I test PASscall on a subset of my single cell data. I used a compute node with 20 CPUs. The program seems work well on the beginning, it successfully generate BED files for each gene. But when it runs the DEEPPASS step, it throws out an error:

`2021-12-12 15:10:23.578735: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-12 15:10:23.869017: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599850000 Hz
2021-12-12 15:10:23.873022: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561b4c596040 executing computations on platform Host. Devices:
2021-12-12 15:10:23.873189: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2021-12-12 15:10:23.907837: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-12-12 15:10:24.174749: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-12-12 15:10:24.175513: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c12b01n01): /proc/driver/nvidia/version does not exist

********************** Start Data Processing **************************

********************** Finished Data Processing ***********************

************************* Start Prediction ****************************

********************** Finished Prediction ****************************
`

Does it mean that I have to use GPU to finish this step? But I have very limited GPU cores and I'd like to use  CPU to calculate per-gene peaks as it is very very time cosuming. Could you help me figure out this problem?

**Comment by YangShi-PKU** [comment]
Above is the log file for exonic peak call. Although it outputs an error, it seem "Finished". But for the "3primeExtented" peak call, it fails directly, below is the log file:
`2021-12-12 15:10:39.771155: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-12 15:10:39.783300: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599850000 Hz
2021-12-12 15:10:39.786053: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b3743d29f0 executing computations on platform Host. Devices:
2021-12-12 15:10:39.786150: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2021-12-12 15:10:39.791798: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-12-12 15:10:39.994161: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-12-12 15:10:39.994271: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c12b01n01): /proc/driver/nvidia/version does not exist

********************** Start Data Processing **************************
Traceback (most recent call last):
  File "/home/ruibinxi_pkuhpc/lustre1/shiyang/software/SCAPTURE-main/DeepPASS/Predict.py", line 69, in <module>
    dataset_pre = pd.read_csv(pre_f,sep='\t',index_col = False,header = None)
  File "/home/ruibinxi_pkuhpc/lustre1/shiyang/software/anaconda3_new/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ruibinxi_pkuhpc/lustre1/shiyang/software/anaconda3_new/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/ruibinxi_pkuhpc/lustre1/shiyang/software/anaconda3_new/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/ruibinxi_pkuhpc/lustre1/shiyang/software/anaconda3_new/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ruibinxi_pkuhpc/lustre1/shiyang/software/anaconda3_new/envs/SCAPTURE_env/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
`
And the output file ".3primeExtended.peaks.evaluated.bed" only contains 1 line: 0    NA    NA.

**Comment by YangShi-PKU** [comment]
[conda_env_list.txt](https://github.com/YangLab/SCAPTURE/files/7698318/conda_env_list.txt)
This is the package info in my conda env. Thanks in advance!

**Comment by liguowei-CAS** [comment]
Hi Yang,

It seems that the DeepPASS step has successfully finished. You can check the 14th column of output bed file (with a suffix of "peaks.evaluated.bed"), which should be predicted labels "positive" or "negative".

The error could be ignored because TensorFlow will use CPU instead if no available GPU is detected, and the prediction step is quite fast. To be frank, the most time-consuming step is actually calling PASs per gene and it's a limitation of single-cell PAS tools.

Best,
Guo-Wei.

**Comment by YangShi-PKU** [comment]
Thanks for your reply! It's of great help to me!

Best
Yang
